import type {
  GameEvent,
  MarketContract,
  Neighborhood,
  PropertyCard,
  RivalState,
} from "./types";

export const NEIGHBORHOODS: Neighborhood[] = [
  { id: "downtown", name: "Downtown", x: 0, z: 0, fabric: "downtown" },
  { id: "scioto-mile", name: "Scioto Mile", x: -0.55, z: -0.55, fabric: "riverfront" },
  { id: "arena", name: "Arena District", x: -0.95, z: 0.55, fabric: "arena" },
  { id: "short-north", name: "Short North", x: -0.7, z: 1.65, fabric: "brick" },
  { id: "victorian", name: "Victorian Village", x: -1.55, z: 1.15, fabric: "village" },
  { id: "university", name: "University District", x: -1.35, z: 2.25, fabric: "brick" },
  { id: "german-village", name: "German Village", x: 0.7, z: -1.65, fabric: "village" },
  { id: "brewery", name: "Brewery District", x: 0.2, z: -1.1, fabric: "brick" },
  { id: "franklinton", name: "Franklinton", x: -1.85, z: -0.75, fabric: "industrial" },
  { id: "grandview", name: "Grandview Heights", x: -2.85, z: 0.35, fabric: "brick" },
  { id: "upper-arlington", name: "Upper Arlington", x: -2.95, z: 1.95, fabric: "suburban" },
  { id: "clintonville", name: "Clintonville", x: -0.85, z: 2.95, fabric: "suburban" },
  { id: "bexley", name: "Bexley", x: 2.45, z: 0.3, fabric: "suburban" },
  { id: "easton", name: "Easton", x: 3.85, z: 1.5, fabric: "retail" },
  { id: "new-albany", name: "New Albany", x: 4.45, z: 2.85, fabric: "campus" },
  { id: "polaris", name: "Polaris Fashion District", x: 1.55, z: 4.25, fabric: "retail" },
  { id: "dublin", name: "Dublin Bridge Street", x: -3.85, z: 3.15, fabric: "retail" },
  { id: "hilliard", name: "Hilliard Tech Park", x: -4.45, z: 1.15, fabric: "industrial" },
  { id: "rickenbacker", name: "Rickenbacker Corridor", x: 2.25, z: -3.85, fabric: "industrial" },
  { id: "groveport", name: "Groveport Logistics Park", x: 3.45, z: -4.05, fabric: "industrial" },
];

export const MAP_TILES: Record<string, [number, number]> = Object.fromEntries(
  NEIGHBORHOODS.map((n) => [n.name, [n.x, n.z] as [number, number]]),
);

export const TOTAL_TILES = NEIGHBORHOODS.length;

export const PROPERTY_CARDS: PropertyCard[] = [
  {
    id: "clintonville-bungalow",
    name: "Clintonville Bungalow Court",
    neighborhood: "Clintonville",
    category: "residential",
    subtype: "Residential",
    cost: 140,
    baseRent: 9,
    ability: "On play: +50 Axis Coin. Cheap entry to the north side.",
    abilityKey: "starter-boost",
    rarity: "common",
    flavor: "Porch lights stay on for the block meeting.",
    art: "/cards/clintonville-bungalow.jpg",
  },
  {
    id: "german-village-row",
    name: "German Village Brick Row",
    neighborhood: "German Village",
    category: "residential",
    subtype: "Residential",
    cost: 160,
    baseRent: 11,
    ability: "Passive: +1 rent for every other residential you own.",
    abilityKey: "adjacency-residential",
    rarity: "common",
    flavor: "Brick that outlasted three mayors and a flood.",
    art: "/cards/german-village-row.jpg",
  },
  {
    id: "dublin-bridge",
    name: "Dublin Bridge Street Retail",
    neighborhood: "Dublin Bridge Street",
    category: "commercial",
    subtype: "Retail",
    cost: 210,
    baseRent: 14,
    ability: "On play: commercial average YES +3¢ for 8 ticks.",
    abilityKey: "com-avg-bump",
    rarity: "common",
    flavor: "Limestone, river, and a wait-list at every door.",
    art: "/cards/dublin-bridge.jpg",
  },
  {
    id: "short-north-condo",
    name: "Short North Condo Block",
    neighborhood: "Short North",
    category: "residential",
    subtype: "Residential",
    cost: 180,
    baseRent: 12,
    ability: "On play: +4¢ bias to Short North inventory markets.",
    abilityKey: "bias-short-north",
    rarity: "uncommon",
    flavor: "Gallery Row prices itself in the dark.",
    art: "/cards/short-north-condo.jpg",
  },
  {
    id: "franklinton-arts",
    name: "Franklinton Arts Warehouse",
    neighborhood: "Franklinton",
    category: "commercial",
    subtype: "Mixed-Use",
    cost: 175,
    baseRent: 11,
    ability: "On play: inventory surge across residential tape.",
    abilityKey: "counter-surge",
    rarity: "common",
    flavor: "The west bank finally got its windows.",
    art: "/cards/franklinton-arts.jpg",
  },
  {
    id: "grandview-loft",
    name: "Grandview Heights Loft Row",
    neighborhood: "Grandview Heights",
    category: "residential",
    subtype: "Residential",
    cost: 170,
    baseRent: 11,
    ability: "Passive: +1 rent for every retail property you own.",
    abilityKey: "retail-adjacency",
    rarity: "common",
    flavor: "The hill still looks down on the river.",
    art: "/cards/grandview-loft.jpg",
  },
  {
    id: "bexley-tudor",
    name: "Bexley Tudor Court",
    neighborhood: "Bexley",
    category: "residential",
    subtype: "Residential",
    cost: 220,
    baseRent: 15,
    ability: "On play: +3¢ bias to metro housing-supply markets.",
    abilityKey: "bias-metro",
    rarity: "uncommon",
    flavor: "Leaded glass and a lawn that never browned.",
    art: "/cards/bexley-tudor.jpg",
  },
  {
    id: "upper-arlington",
    name: "Upper Arlington Estate Lot",
    neighborhood: "Upper Arlington",
    category: "residential",
    subtype: "Residential",
    cost: 260,
    baseRent: 18,
    ability: "Passive +2 rent while metro supply is tight.",
    abilityKey: "tight-supply-rent",
    rarity: "uncommon",
    flavor: "The circle drive is the whole argument.",
    art: "/cards/upper-arlington.jpg",
  },
  {
    id: "victorian-row",
    name: "Victorian Village Painted Lady",
    neighborhood: "Victorian Village",
    category: "residential",
    subtype: "Residential",
    cost: 195,
    baseRent: 13,
    ability: "Passive: +2 rent if you also own Short North.",
    abilityKey: "short-north-adj",
    rarity: "uncommon",
    flavor: "Turrets catch the High Street spill.",
    art: "/cards/victorian-row.jpg",
  },
  {
    id: "university-row",
    name: "University District High Street",
    neighborhood: "University District",
    category: "residential",
    subtype: "Mixed-Use",
    cost: 200,
    baseRent: 13,
    ability: "On play: +40 Axis Coin. Game-day events pay you extra.",
    abilityKey: "osu-boost",
    rarity: "uncommon",
    flavor: "The street never really sleeps in October.",
    art: "/cards/university-row.jpg",
  },
  {
    id: "polaris-retail",
    name: "Polaris Fashion Anchor",
    neighborhood: "Polaris Fashion District",
    category: "commercial",
    subtype: "Retail",
    cost: 240,
    baseRent: 16,
    ability: "On play: +6¢ to retail foot-traffic for the session.",
    abilityKey: "retail-boost",
    rarity: "uncommon",
    flavor: "North-side gravity, measured in parking stalls.",
    art: "/cards/polaris-retail.jpg",
  },
  {
    id: "hilliard-flex",
    name: "Hilliard Tech Flex Campus",
    neighborhood: "Hilliard Tech Park",
    category: "commercial",
    subtype: "Industrial",
    cost: 250,
    baseRent: 17,
    ability: "Passive: +2 rent while Logistics Boom is above 55¢.",
    abilityKey: "logistics-rent",
    rarity: "uncommon",
    flavor: "Loading docks dressed as a campus.",
    art: "/cards/hilliard-flex.jpg",
  },
  {
    id: "rickenbacker-logistics",
    name: "Rickenbacker Distribution Hub",
    neighborhood: "Rickenbacker Corridor",
    category: "commercial",
    subtype: "Industrial",
    cost: 290,
    baseRent: 20,
    ability: "Passive: Logistics Boom events grant double Axis Coin.",
    abilityKey: "logistics-double",
    rarity: "uncommon",
    flavor: "Air freight does not wait on a committee.",
    art: "/cards/rickenbacker-logistics.jpg",
  },
  {
    id: "groveport-industrial",
    name: "Groveport Logistics Park",
    neighborhood: "Groveport Logistics Park",
    category: "commercial",
    subtype: "Industrial",
    cost: 270,
    baseRent: 19,
    ability: "Industrial synergy: +3 rent if you also own Rickenbacker.",
    abilityKey: "industrial-synergy",
    rarity: "uncommon",
    flavor: "The south corridor is one long truck court.",
    art: "/cards/groveport-industrial.jpg",
  },
  {
    id: "downtown-office",
    name: "Downtown Office Tower",
    neighborhood: "Downtown",
    category: "commercial",
    subtype: "Office",
    cost: 320,
    baseRent: 22,
    ability: "On play: conversion-incentive pressure on office markets.",
    abilityKey: "conversion-pressure",
    rarity: "rare",
    flavor: "The crown still faces the river.",
    art: "/cards/downtown-office.jpg",
  },
  {
    id: "arena-district-mixed",
    name: "Arena District Mixed-Use",
    neighborhood: "Arena District",
    category: "commercial",
    subtype: "Mixed-Use",
    cost: 350,
    baseRent: 24,
    ability: "Counts as both Residential and Commercial for Dominion.",
    abilityKey: "dual-count",
    rarity: "rare",
    flavor: "A roof that fills on a Tuesday in January.",
    art: "/cards/arena-district-mixed.jpg",
  },
  {
    id: "easton-town",
    name: "Easton Town Center Block",
    neighborhood: "Easton",
    category: "commercial",
    subtype: "Retail",
    cost: 310,
    baseRent: 21,
    ability: "On play: +5¢ to retail traffic and commercial average.",
    abilityKey: "easton-cluster",
    rarity: "rare",
    flavor: "The roundabout is a balance sheet.",
    art: "/cards/easton-town.jpg",
  },
  {
    id: "scioto-mile-tower",
    name: "Scioto Mile River Tower",
    neighborhood: "Scioto Mile",
    category: "residential",
    subtype: "Mixed-Use",
    cost: 340,
    baseRent: 23,
    ability: "Passive: +3 rent if you also own Downtown.",
    abilityKey: "downtown-adj",
    rarity: "rare",
    flavor: "Every unit faces the water. Every bid faces you.",
    art: "/cards/scioto-mile-tower.jpg",
  },
  {
    id: "new-albany-campus",
    name: "New Albany / Intel Corridor Site",
    neighborhood: "New Albany",
    category: "commercial",
    subtype: "Office",
    cost: 380,
    baseRent: 28,
    ability: "While owned: Intel-timeline markets cannot crash below 35¢.",
    abilityKey: "intel-floor",
    rarity: "legendary",
    flavor: "The fab is a horizon. The horizon is a floor.",
    art: "/cards/new-albany-campus.jpg",
  },
  {
    id: "brewery-lofts",
    name: "Brewery District Malt Lofts",
    neighborhood: "Brewery District",
    category: "commercial",
    subtype: "Mixed-Use",
    cost: 230,
    baseRent: 16,
    ability: "Passive: +1 rent for every Mixed-Use you own.",
    abilityKey: "mixed-adjacency",
    rarity: "uncommon",
    flavor: "The stacks still pretend they steam.",
    art: "/cards/brewery-lofts.jpg",
  },
];

export const STARTER_HAND_IDS = [
  "clintonville-bungalow",
  "german-village-row",
  "dublin-bridge",
];

export const MARKET_DEFS: Omit<MarketContract, "yesCents" | "fairCents" | "history">[] = [
  {
    id: "sn-inventory",
    name: "Short North inventory",
    question: "Will Short North condo inventory stay under two months?",
    sector: "residential",
  },
  {
    id: "office-conversion",
    name: "Office conversion",
    question: "Will downtown Class B conversion incentives clear this window?",
    sector: "office",
  },
  {
    id: "intel-timeline",
    name: "Intel New Albany",
    question: "Will the Intel Ohio fab hit a volume-production print?",
    sector: "intel",
  },
  {
    id: "retail-traffic",
    name: "Retail foot traffic",
    question: "Will Polaris / Easton weekend traffic beat the 2019 baseline?",
    sector: "retail",
  },
  {
    id: "logistics-boom",
    name: "Logistics boom",
    question: "Will Rickenbacker air-cargo volumes print a new high?",
    sector: "industrial",
  },
  {
    id: "metro-supply",
    name: "Metro housing supply",
    question: "Will Franklin County remain a seller's market?",
    sector: "metro",
  },
  {
    id: "com-average",
    name: "Commercial average",
    question: "Will the commercial YES tape close above 50¢ this cycle?",
    sector: "commercial",
  },
];

export function seedMarkets(): MarketContract[] {
  const opens: Record<string, number> = {
    "sn-inventory": 48,
    "office-conversion": 41,
    "intel-timeline": 52,
    "retail-traffic": 46,
    "logistics-boom": 50,
    "metro-supply": 57,
    "com-average": 44,
  };
  return MARKET_DEFS.map((def) => {
    const open = opens[def.id] ?? 50;
    return { ...def, yesCents: open, fairCents: open, history: [open] };
  });
}

export function seedRivals(): RivalState[] {
  return [
    {
      id: "scioto-capital",
      name: "Scioto Capital",
      color: "#5b7388",
      personality: "commercial",
      coin: 720,
      ownedIds: [],
    },
    {
      id: "buckeye-land",
      name: "Buckeye Land",
      color: "#6a7a52",
      personality: "residential",
      coin: 680,
      ownedIds: [],
    },
  ];
}

export const EVENTS: GameEvent[] = [
  {
    id: "osu-gameday",
    title: "Home Saturday",
    body: "The Horseshoe fills. High Street and the Arena spill cash into retail tape.",
    coinDelta: 0,
    shock: { "retail-traffic": 8, "sn-inventory": 3 },
    log: "OSU Saturday. Retail tape rips higher.",
  },
  {
    id: "polar-vortex",
    title: "Polar Vortex",
    body: "A Canadian high sits on the Scioto. Rents freeze. Industrial holds.",
    coinDelta: -30,
    shock: { "retail-traffic": -6, "metro-supply": -3 },
    rentMult: 0.72,
    log: "Polar vortex. Collections thin. Warehouses stay warm.",
  },
  {
    id: "intel-delay",
    title: "Fab Slip",
    body: "A tool install slips a quarter. New Albany tape wobbles unless you hold the corridor.",
    coinDelta: 0,
    shock: { "intel-timeline": -10, "com-average": -3 },
    log: "Intel timeline slips. The corridor holds its breath.",
  },
  {
    id: "amazon-expand",
    title: "South Corridor Expansion",
    body: "A logistics giant prints a new box on the Rickenbacker run. Cargo tape rips.",
    coinDelta: 0,
    shock: { "logistics-boom": 12, "com-average": 4 },
    log: "Cargo expansion. Logistics boom reprices.",
  },
  {
    id: "streetscape",
    title: "High Street Grant",
    body: "The city drops a streetscape grant on Short North. Owners collect.",
    coinDelta: 0,
    shock: { "sn-inventory": 5, "retail-traffic": 3 },
    log: "Streetscape grant hits Gallery Row.",
  },
  {
    id: "rate-cut",
    title: "Cut Rumor",
    body: "The wire prints a cut. Every YES bid lifts a few cents.",
    coinDelta: 0,
    shock: { "*": 4 },
    log: "Rate-cut rumor. The whole tape bids.",
  },
  {
    id: "conversion-bill",
    title: "Conversion Bill",
    body: "Class B towers get a path to apartments. Office conversion rips.",
    coinDelta: 0,
    shock: { "office-conversion": 10, "metro-supply": -4 },
    log: "Conversion bill clears committee.",
  },
  {
    id: "housing-tight",
    title: "Listings Dry Up",
    body: "Franklin County inventory prints a new low. Residences collect.",
    coinDelta: 0,
    shock: { "metro-supply": 7, "sn-inventory": 4 },
    log: "Seller's market hardens.",
  },
  {
    id: "cargo-record",
    title: "Cargo Record",
    body: "Rickenbacker prints a record tonnage night. Industrial owners get paid.",
    coinDelta: 0,
    shock: { "logistics-boom": 9 },
    log: "Air-cargo record. The south corridor cashes.",
  },
  {
    id: "office-vacancy",
    title: "Vacancy Print",
    body: "Downtown vacancy prints ugly. Unless conversion is already bid, rents sag.",
    coinDelta: -20,
    shock: { "office-conversion": -5, "com-average": -4 },
    log: "Vacancy print. Class B blinks.",
  },
];

export const cardById = (id: string) => PROPERTY_CARDS.find((c) => c.id === id);

export function fisherYates<T>(items: T[], rand: () => number = Math.random): T[] {
  const next = items.slice();
  for (let i = next.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    const tmp = next[i]!;
    next[i] = next[j]!;
    next[j] = tmp;
  }
  return next;
}

export function neighborhoodByName(name: string) {
  return NEIGHBORHOODS.find((n) => n.name === name);
}

export const SEASONS = ["Winter", "Spring", "Summer", "Autumn"] as const;
export function seasonFor(cycle: number) {
  return SEASONS[(cycle - 1) % 4]!;
}
